# DevBuddy config file
# See https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md

env:
  ENV: development

up:
  - go:
      version: 1.25.3
      modules: true
  # - custom:
  #     name: Install golangci-lint
  #     met?: which golangci-lint && golangci-lint --version | grep -q '2.1.6'
  #     meet: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6
  # - memcached

commands:
  test:
    desc: Run tests
    run: go test -cover -timeout 5s ./...
  fuzz:
    desc: Run tests
    run: go test -fuzz
  integration:
    desc: Run integration tests
    run: go test -v -run TestIntegration
  lint:
    desc: Lint the project
    run: golangci-lint run

open:
  devbuddy: https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md#config-devyml
