# DevBuddy config file
# See https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md

env:
  ENV: development

up:
  - go:
      version: 1.25.3
      modules: true
  # - custom:
  #     name: Install golangci-lint
  #     met?: which golangci-lint && golangci-lint --version | grep -q '2.1.6'
  #     meet: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6
  # - memcached

commands:
  test:
    desc: Run all tests
    run: go test -v ./...

  test-integration:
    desc: Run integration tests (requires memcached on 127.0.0.1:11211)
    run: go test -v -run TestIntegration ./...

  test-client:
    desc: Run client unit tests only
    run: go test -v -run '^TestClient_' .

  test-meta:
    desc: Run meta protocol tests
    run: go test -v ./meta

  bench:
    desc: Run client benchmarks
    run: go test -bench=BenchmarkClient -benchmem -run=^$ .

  bench-pool:
    desc: Run pool benchmarks (both channel and puddle)
    run: go test -tags=puddle -bench=BenchmarkPool -benchmem -run=^$ .

  fuzz:
    desc: Run fuzz tests
    run: go test -fuzz

  lint:
    desc: Lint the project
    run: golangci-lint run

open:
  devbuddy: https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md#config-devyml
