# DevBuddy config file
# See https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md

env:
  ENV: development

up:
  - go:
      version: 1.24.2
      modules: true
  - custom:
      name: Install golangci-lint
      met?: which golangci-lint && golangci-lint --version | grep -q '2.1.6'
      meet: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

commands:
  test:
    desc: Run tests
    run: go test -cover ./...
  lint:
    desc: Lint the project
    run: golangci-lint run

open:
  devbuddy: https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md#config-devyml